### ISSUE TITLE
关于iOS设备几个适配点

### ISSUE THREAD

**Issue by zhongdom** [CarGuo/GSYGithubAppWeex#1]
- 状态栏高度：iPhone X为`44` ，其他设备为 `20`
- 导航栏高度为 `44`
- Tabbar高度为 `49`
- 对于iPhone X，底部工具栏需要为home indicator留出 `34`

**Comment by CarGuo** [comment]
针对ios和ipx做了一点适配，可以看看，如果有更新的方法可以提个pr
