### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by Wanghuayin** [CarGuo/GSYGithubAppWeex#12]
hi，您好，我是闲鱼测试同学，有准备flutter和一些跨端的开发工具的对比，看到您用现在主流的跨端的语言写了3个App，我能否使用您的这3个App做一轮对比测试，文章应该会在一些公共的平台进行分享，到时候会附上您github的地址，您看是否可以，没有您的联系方式，如果可以的话，能加一下我的微信76146462 或者邮件 huayin.why@alibaba-inc.com 我们具体沟通一下吗？万分感谢！

**Comment by CarGuo** [comment]
已经加了，可以啊，不过Weex这个项目做得比较糙了下，哈哈哈。
