### ISSUE TITLE
android 端登录会报ssl错误，需要单独改一下么？

### ISSUE THREAD

**Issue by hiXing** [CarGuo/GSYGithubAppWeex#2]
![image](https://user-images.githubusercontent.com/9985104/39174412-44eabe1a-47da-11e8-9ae7-63d25bd84296.png)

**Comment by CarGuo** [comment]
只要readme中
```
 3、你需要自己项目src/core/common/目录下 创建一个ignoreConfig.js文件，然后输入你申请的Github client_id 和 client_secret。

```
正常可以

**Comment by hiXing** [comment]
我加了这个配置，还是报错了

**Comment by CarGuo** [comment]
这个得你看看，你那边出现问题的具体场景是什么。
我这边目前没有复现，理论是说接口是github的api，默认也不应该有这个问题，特定登录的时候。
你可以看看登录的时候http返回的错误。

**Comment by CarGuo** [comment]
简单的从你的log上看是 usually protocol error，所以比较奇怪

**Comment by hiXing** [comment]
![image](https://user-images.githubusercontent.com/9985104/39177388-c88bce24-47e1-11e8-9fcc-8a0c92d34d64.png)
跟手机系统版本有关系么？我跑在了4.4的机子上

**Comment by hiXing** [comment]
我打包放到小米的8.0系统上，发现，，，没问题，，，，

**Comment by CarGuo** [comment]
看看会不会是在你那边，在原生端json序列化出现了问题

**Comment by hiXing** [comment]
用AS也是报这个错误，不过在8.0上没问题，也确实很好用的，谢谢了，
最近用weex，遇到了好多坑，
