### ISSUE TITLE
请问启动时出现问题

### ISSUE THREAD

**Issue by hkstar35** [CarGuo/GSYGithubAppWeex#20]
ERROR  Failed to compile with 3 errors                                                                                                                                      01:17:25

These relative modules were not found:

* ../common/ignoreConfig in ./src/core/net/user.js
* ../core/common/ignoreConfig in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/EditIssuePage.vue, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/LoginPage.vue

**Comment by CarGuo** [comment]
请看readme

**Comment by hkstar35** [comment]
haode
