### ISSUE TITLE
关于开发过程调试代码

### ISSUE THREAD

**Issue by zhongdom** [CarGuo/GSYGithubAppWeex#3]
你好，非常感谢你开源这个项目，现有几点疑问望解答。
- 开发过程是怎样调试代码的？我用的是mac，命令行运行`weex debug`，然后使用WeexPlayground这个app扫描二维码，然而只是能调试这个app，而不是自己要开发的app，请问正确的调试姿势是怎样的？
- 项目中有使用`gsyWeb`这个原生组件，但对应iOS项目目录中并未找到对应的`CustomWebComponent`文件，注册代码也被注释掉了，为什么呢？

**Comment by CarGuo** [comment]
1、我一般都是直接看log输出调试的，weex debug不是很好用，所以我直接通过命令行tail -f console.log去跟踪。然后如果你需要继承调试，你需要参考WeexPlayground源码，继承二维码扫描调试功能。

2、CustomWebComponent做了一半，忽然发现官网已经更新了我想要的功能，只是还没发布，所以ios的就暂停了。
