### ISSUE TITLE
1. 关于APK登陆无效问题

### ISSUE THREAD

**Issue by njuptzwt** [CarGuo/GSYGithubAppWeex#34]
1. 作者你好。我最近在对比rn，flutter，weex的性能比较。刚好看到你这有各类同款APP，非常感谢。目前Weex的这个项目我本地应该是版本问题编译不过了，然后使用已有的APP登陆，github账号无效且没有报错信息。我的手机是Android10，请问Weex这个还维护吗，又直接能用的APP吗，谢谢

**Comment by njuptzwt** [comment]
好吧，weex太难用了。把环境配置好之后（node的版本是14.15.1才能运行），发现这个github的Oauth请求接口过期了，作者已经不在维护了吧。那就不研究这玩意了

**Comment by CarGuo** [comment]
Weex 暂时不维护了，除非有新的weex更新
