### ISSUE TITLE
你是怎么加载本地图片的？

### ISSUE THREAD

**Issue by YQjiuhao** [CarGuo/GSYGithubAppWeex#5]
我在新建一个demo中使用了本地图片，但是不能打包到APP中，你是怎么打包进去的？我看你的静态资源(static)都能导进APP项目中

**Comment by YQjiuhao** [comment]
我看了，但是我在weex项目中看到你放在iOS平台的根目录，在XCode中打开看到放在了Resource里面了，这个也是自己拷贝进去的吗？

**Comment by CarGuo** [comment]
因为xcode是通过link的，和在哪个目录下关系不太大，只要不太大

**Comment by YQjiuhao** [comment]
好的，谢谢
