### ISSUE TITLE
您好！在使用navigator.push进行界面跳转的时候，目录文件调用了外部组件，转化.js格式的时候会报错，你是咋解决的啊！

### ISSUE THREAD

**Issue by cyl123** [CarGuo/GSYGithubAppWeex#7]

**Comment by CarGuo** [comment]
多页面js文件？？？首先看看demo的webpack针对weex的js文件生成。然后再看看是否配置了新页面对js文件的拦截加载

**Comment by cyl123** [comment]
就是在使用navigator.push跳到SearchPage的界面，在SearchPage.vue生成.js的时候，引用组件 import NavigationBar from '@/components/NavigationBar.vue' 就会报错

**Comment by CarGuo** [comment]
SearchPage.vue 中，引用的应该是相对路径，不带@的，@的处理我印象中，一般都是在entry文件中使用
```
import NavigationBar from './widget/NavigationBar.vue'
```

**Comment by cyl123** [comment]
转换js使用的是weex compile src/components/SearchPage.vue dis-m  这个么？？？

**Comment by CarGuo** [comment]
不是，是https://github.com/CarGuo/GSYGithubAppWeex/blob/master/configs/webpack.common.conf.js，这里面
```
const weexEntry = {
  'index': helper.root('entry.js'),
  'RepositoryDetailPage': helper.root('entry/RepositoryDetailPage.js'),
  'UserInfoPage': helper.root('entry/UserInfoPage.js'),
  'CodeDetailPage': helper.root('entry/CodeDetailPage.js'),
  'IssueDetailPage': helper.root('entry/IssueDetailPage.js'),
  'CommonListPage': helper.root('entry/CommonListPage.js'),
  'SearchPage': helper.root('entry/SearchPage.js'),
  'WebPage': helper.root('entry/WebPage.js'),
  'EditIssuePage': helper.root('entry/EditIssuePage.js'),
  'SettingPage': helper.root('entry/SettingPage.js'),
}

```
添加入口文件，客户端通过weex配置，在编译是自动生成。

跳转的时候也是分客户端和web端的https://github.com/CarGuo/GSYGithubAppWeex/blob/master/src/mixins/index.js

**Comment by cyl123** [comment]
好的。非常感谢大神！
