### ISSUE TITLE
请教个问题：所有页面公用router.js，应该会出现加载多余页面，浪费资源问题吧？

### ISSUE THREAD

**Issue by liushengyi** [CarGuo/GSYGithubAppWeex#9]
如题！

**Comment by CarGuo** [comment]
路由的概念是，就如同一个表，做了关联而已，方便你管理和在指定对应key的时候，跳转加载对应页面。其次，vue文件是没办法直接被使用的

在web中是被编译成一个.js文件，然后才加载，而这个js文件不做处理，本来就是一个单页面而已。

在原生中也是，然后原生模块使用的是多页面形式，对于每个页面的vue，其实是变成成了一个一个独立的js文件，比如CodeDetailPage.vue最后变成了CodeDetailPage.js。然后比如我打开了CodeDetailPage页面，Activity才去加载CodeDetailPage.js。

这里web端和原生端跳转的不同处理是在mixins/中处理的。
打包配置是在configs下
生成js文件在dist中可见。

**Comment by liushengyi** [comment]
这个我测试过，如果你在router中引用了vue文件，该vue文件会被编译到生成的js文件中。这样，生成的js文件体积肯定会变大。

**Comment by CarGuo** [comment]
我想我知道你的意思了。
在web端是正常的，因为web端需要引用到所有vue页面，通过入口文件entry打包成一个单独的jsbundle，所以router公用没有问题。
但是在native端，多页面下，多个entry文件都使用同一个router文件，导致多页面的每一个jsbundle都带有全部的vue文件引用，导致变大。

应该说和entry文件有关，那时候黏贴复制过啦，在多页面的entry文件里，其实都不需要router，因为都页面下router完全不共享。

**Comment by liushengyi** [comment]
是的，大致是这个意思。
但是，web你目前是单页面，所有不会有问题，如果是多页面，也有同样问题。
native如果不用router，是没有问题的。

**Comment by liushengyi** [comment]
我觉得native也可以根据业务逻辑划分多个单页面应用（每个单页面对应一个entry.js和router.js），单页面之间可以用navigator跳转，但是进入entry之后,router还是根据锚点跳转对应真正页面。  这样可以防止编译后页面数量过多不好维护的问题

**Comment by CarGuo** [comment]
这个倒是可以根据业务需要这么做，其实项目里也有这样的配置，比入personPage到setting的就是走了router
